### ISSUE TITLE
Install Error (getch)

### ISSUE THREAD

**Issue by KyleKing** [gergelyk/peepshow#2]
Hi, I wanted to try out peepshow, but I couldn't install the getch dependency on Python 3.8 / Mac. From the peepshow requirements, [getch](https://pypi.org/project/getch/) hasn't been updated since 2013 and I wasn't able to find the source code

[py-getch](https://pypi.org/project/py-getch/) was last released in 2015, but is on [Github and was last updated in 2019](https://github.com/joeyespo/py-getch/commits/master). I'm not sure if py-getch is a drop-in replacement for single character input or if there is a better, maintained option

<details>
<summary>Full Install Error</summary>
<pre>
 Installing collected packages: getch
      Running setup.py install for getch: started
      Running setup.py install for getch: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/kyleking/Developer/My-Programming-Sketchbook/Assorted_Snippets/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1f/gd24l7210d3d8crp0clcm4440000gn/T/pip-req-build-0ed11468/setup.py'"'"'; __file__='"'"'/private/var/folders/1f/gd24l7210d3d8crp0clcm4440000gn/T/pip-req-build-0ed11468/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1f/gd24l7210d3d8crp0clcm4440000gn/T/pip-record-2kjp2xqk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/kyleking/Developer/My-Programming-Sketchbook/Assorted_Snippets/.venv/include/site/python3.8/getch
           cwd: /private/var/folders/1f/gd24l7210d3d8crp0clcm4440000gn/T/pip-req-build-0ed11468/
      Complete output (21 lines):
      running install
      running build
      running build_ext
      building 'getch' extension
      creating build
      creating build/temp.macosx-10.9-x86_64-3.8
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Caskroom/miniconda/base/include -arch x86_64 -I/usr/local/Caskroom/miniconda/base/include -arch x86_64 -I/usr/local/include -I/usr/include -I/Users/kyleking/Developer/My-Programming-Sketchbook/Assorted_Snippets/.venv/include -I/usr/local/Caskroom/miniconda/base/include/python3.8 -c getchmodule.c -o build/temp.macosx-10.9-x86_64-3.8/getchmodule.o
      getchmodule.c:38:6: warning: unused variable 'ok' [-Wunused-variable]
              int ok = PyArg_ParseTuple(args, "");
                  ^
      getchmodule.c:45:6: warning: unused variable 'ok' [-Wunused-variable]
              int ok = PyArg_ParseTuple(args, "");
                  ^
      getchmodule.c:58:9: error: implicit declaration of function 'Py_InitModule' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              (void) Py_InitModule("getch", GetchMethods);
                     ^
      getchmodule.c:59:1: warning: non-void function does not return a value [-Wreturn-type]
      }
      ^
      3 warnings and 1 error generated.
      error: command 'gcc' failed with exit status 1
</pre>
</details

**Comment by gergelyk** [comment]
Good suggestion. Thank you!
